# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

stages:

- stage: Build_stage
  displayName: 'Build Stage'
  jobs:
    - job: Build
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'

      - script: |
          npm install -g @angular/cli
          npm install
          npm run build
        displayName: 'npm install and build'

      - publish: $(System.DefaultWorkingDirectory)/build
        artifact: WebApp
        displayName: 'Publish artifacts'

- stage: Deploy_stage
  displayName: "Deploy Stage"
  jobs:
    - job: Deploy
      pool:
        vmImage: 'windows-latest'
      steps:

      - download: current
        artifact: WebApp
        displayName: 'Retrieve artifacts'
      - task: AzureFileCopy@4
        inputs:
          SourcePath: '$(Pipeline.Workspace)/WebApp'
          azureSubscription: 'Pay-as-you-go(839b8638-287d-45d0-8a3c-dcaef5eac35f)'
          Destination: 'AzureBlob'
          storage: 'stfrontendproject1'
          ContainerName: '$web'
        displayName: 'Deploy to Azure storage account'
