
trigger:
- master

variables:
  artifactName: WebApp
  
stages:

- stage: Build_stage
  displayName: 'Build Stage'

  jobs:
    - job: Build
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'

      - script: |
          npm install -g @angular/cli
          npm install
          npm run build
        displayName: 'npm install and build'

      - publish: $(Build.SourcesDirectory)/dist
        artifact: $(artifactName)
        displayName: 'Publish artifacts'

- stage: Deploy_stage
  displayName: "Deploy Stage"
  jobs:
    - job: Deploy
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - checkout: none

      - download: current
        artifact: $(artifactName)
        displayName: 'Retrieve artifacts'

      - task: AzureCLI@2
        inputs:
          azureSubscription: $(subscription)
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: 'az storage blob delete-batch --account-name $(storageAccount) --source \$web --auth-mode login'
        displayName: 'Empty storage container'

      - task: AzureCLI@2
        inputs:
          azureSubscription: $(subscription)
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: 'az storage blob upload-batch -d \$web --source $(Pipeline.Workspace)/$(artifactName) --account-name $(storageAccount) --auth-mode login'
        displayName: 'Deploy to Azure Storage account'
