
trigger:
- master

stages:

- stage: Build_stage
  displayName: 'Build Stage'
  jobs:
    - job: Build
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'

      - script: |
          npm install -g @angular/cli
          npm install
          npm run build
        displayName: 'npm install and build'

      - publish: $(Build.SourcesDirectory)/dist
        artifact: WebApp
        displayName: 'Publish artifacts'

- stage: Deploy_stage
  variables:
    storageAccount: stfrontendproject1
  displayName: "Deploy Stage"
  jobs:
    - job: Deploy
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - checkout: none

      - download: current
        artifact: WebApp
        displayName: 'Retrieve artifacts'

      - task: AzureCLI@2
        inputs:
          azureSubscription: 'Pay-as-you-go(839b8638-287d-45d0-8a3c-dcaef5eac35f)'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: 'az storage blob delete-batch --account-name $(storageAccount) --source \$web --auth-mode login'
        displayName: 'Empty storage container'

      - task: AzureCLI@2
        inputs:
          azureSubscription: 'Pay-as-you-go(839b8638-287d-45d0-8a3c-dcaef5eac35f)'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: 'az storage blob upload-batch -d \$web --source $(Pipeline.Workspace)/WebApp --account-name $(storageAccount) --auth-mode login'
        displayName: 'Deploy to Azure Storage account'

# The official AzureFileCopy Tsak does not work, because the mime types for the js files are not set correctly
#      - task: AzureFileCopy@4
#        inputs:
#          SourcePath: '''
#          azureSubscription: 'Pay-as-you-go(839b8638-287d-45d0-8a3c-dcaef5eac35f)'
#          Destination: 'AzureBlob'
#          storage: 'stfrontendproject1'
#          ContainerName: '$web'
#        displayName: 'Deploy to Azure storage account'
